"""add_location_and_platform_to_tickets

Revision ID: 1c010fe04ff3
Revises: baaaadb54c91
Create Date: 2026-02-12 01:26:32.639156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c010fe04ff3'
down_revision: Union[str, None] = 'baaaadb54c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
