"""add_soc_siem_fields

Revision ID: 2d56fe699630
Revises: 81a495feba15
Create Date: 2026-01-28 05:43:01.585987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d56fe699630'
down_revision: Union[str, None] = '81a495feba15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('raw_event', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('parsed_event', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('enrichment', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('remediation_suggestions', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('siem_metadata', sa.JSON(), nullable=True))
    op.add_column('tickets', sa.Column('final_severity', sa.String(length=20), nullable=True))
    op.add_column('tickets', sa.Column('correlation_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'correlation_tags')
    op.drop_column('tickets', 'final_severity')
    op.drop_column('tickets', 'siem_metadata')
    op.drop_column('tickets', 'remediation_suggestions')
    op.drop_column('tickets', 'enrichment')
    op.drop_column('tickets', 'parsed_event')
    op.drop_column('tickets', 'raw_event')
    # ### end Alembic commands ###
