"""add_platform_to_ticket

Revision ID: 353cecd64b71
Revises: 2d56fe699630
Create Date: 2026-01-28 08:00:31.052563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353cecd64b71'
down_revision: Union[str, None] = '2d56fe699630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('platform', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'platform')
    # ### end Alembic commands ###
