"""sync_all_models

Revision ID: 3d27031ee8c7
Revises: 78a3b78a5efc
Create Date: 2026-02-14 18:29:40.372363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d27031ee8c7'
down_revision: Union[str, None] = '78a3b78a5efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_global', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_global')
    # ### end Alembic commands ###
