"""add_security_flags_to_user

Revision ID: 4511119088ae
Revises: c2c47c740150
Create Date: 2026-01-26 01:25:04.740155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4511119088ae'
down_revision: Union[str, None] = 'c2c47c740150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Manejo de Forms: añadir nueva columna permitiendo nulos primero
    op.add_column('forms', sa.Column('fields_schema', sa.JSON(), nullable=True))
    # Copiar datos de 'schema' a 'fields_schema'
    op.execute("UPDATE forms SET fields_schema = schema")
    # Ahora sí poner NOT NULL y borrar la vieja
    op.alter_column('forms', 'fields_schema', nullable=False)
    op.drop_column('forms', 'schema')

    # 2. Manejo de Users: añadir columnas permitiendo nulos
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reset_2fa_next_login', sa.Boolean(), nullable=True))
    
    # Asignar valor por defecto a registros existentes
    op.execute("UPDATE users SET force_password_change = False")
    op.execute("UPDATE users SET reset_2fa_next_login = False")
    
    # Ahora establecer NOT NULL
    op.alter_column('users', 'force_password_change', nullable=False)
    op.alter_column('users', 'reset_2fa_next_login', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_2fa_next_login')
    op.drop_column('users', 'force_password_change')
    op.add_column('forms', sa.Column('schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('forms', 'fields_schema')
    # ### end Alembic commands ###
