"""Add full_name, role columns and make group_id nullable to users table

Revision ID: 601ed2a3a16c
Revises: f1a4abe81fcf
Create Date: 2026-01-31 17:56:09.802893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601ed2a3a16c'
down_revision: Union[str, None] = 'f1a4abe81fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True, server_default='user'))
    op.alter_column('users', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # Remove server_default after column is added for existing rows
    op.alter_column('users', 'full_name', server_default=None)
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'full_name')
    op.alter_column('users', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###