"""fix_missing_columns

Revision ID: 78a3b78a5efc
Revises: 1c010fe04ff3
Create Date: 2026-02-12 02:04:17.926254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a3b78a5efc'
down_revision: Union[str, None] = '1c010fe04ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'location_nodes', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'location_id')
    # ### end Alembic commands ###
