"""Correct user table schema and seed initial data

Revision ID: 8cb177b16662
Revises: f1a4abe81fcf
Create Date: 2026-01-31 18:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid
from sqlalchemy.sql import func # Import func for server_default
from app.core.security import get_password_hash
from app.schemas.user import UserRole # Assuming UserRole is defined here

# revision identifiers, used by Alembic.
revision: str = '8cb177b16662'
down_revision: Union[str, None] = '601ed2a3a16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Seed initial data: Group, Role, User ###

    # Define table helpers
    groups_table = sa.table(
        "groups",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("parent_id", sa.UUID)
    )

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID),
        sa.column("name", sa.String),
        sa.column("description", sa.String)
    )

    user_roles_table = sa.table(
        "user_roles", # Association table
        sa.column("user_id", sa.UUID),
        sa.column("role_id", sa.UUID)
    )

    # --- Create Root Group 'Administradores' ---
    administradores_group_id = uuid.uuid4()
    op.bulk_insert(groups_table, [
        {'id': administradores_group_id, 'name': 'Administradores', 'parent_id': None, 'description': 'Root group for administrators'},
    ])

    # --- Create Role 'superadmin' (mapping to ADMIN) ---
    # We assume 'admin' role needs to be seeded if it doesn't exist.
    admin_role_id = uuid.uuid4() 
    op.bulk_insert(roles_table, [
        {'id': admin_role_id, 'name': UserRole.ADMIN.value, 'description': 'Super administrator role'},
    ])
    
    # --- Create Admin User ---
    users_table = sa.table(
        "users",
        sa.column("id", sa.UUID),
        sa.column("username", sa.String),
        sa.column("email", sa.String),
        sa.column("hashed_password", sa.String),
        sa.column("first_name", sa.String),
        sa.column("last_name", sa.String),
        sa.column("full_name", sa.String),
        sa.column("is_active", sa.Boolean),
        sa.column("is_superuser", sa.Boolean),
        sa.column("group_id", sa.UUID),
        sa.column("preferred_language", sa.String),
        sa.column("is_2fa_enabled", sa.Boolean),
        sa.column("totp_secret", sa.String),
        sa.column("recovery_codes", sa.ARRAY(sa.Text)),
        sa.Column('failed_login_attempts', sa.Integer),
        sa.Column('locked_until', sa.DateTime),
        sa.Column('force_password_change', sa.Boolean),
        sa.Column('reset_2fa_next_login', sa.Boolean),
        sa.Column('enroll_2fa_mandatory', sa.Boolean),
        sa.Column('created_at', sa.DateTime),
        sa.Column('updated_at', sa.DateTime),
        sa.Column('deleted_at', sa.DateTime),
    )

    admin_user_id = uuid.uuid4()
    admin_email = "admin@example.com"
    admin_username = "admin"
    admin_password = "adminpassword" # User specified password
    hashed_password = get_password_hash(admin_password)

    op.bulk_insert(
        users_table,
        [
            {
                "id": admin_user_id,
                "username": admin_username,
                "email": admin_email,
                "hashed_password": hashed_password,
                "first_name": "Admin",
                "last_name": "User",
                "full_name": "Admin User",
                "is_active": True,
                "is_superuser": True, # Keep as True for initial admin
                "group_id": administradores_group_id, # Link to the created group
                "preferred_language": "es",
                "is_2fa_enabled": False, # As requested
                "totp_secret": None,
                "recovery_codes": None,
                "failed_login_attempts": 0,
                "locked_until": None,
                "force_password_change": False, # As requested
                "reset_2fa_next_login": False, # As requested
                "enroll_2fa_mandatory": False, # As requested
                "created_at": func.now(),
                "updated_at": func.now(),
                "deleted_at": None,
            }
        ],
    )
    
    # Link admin user to the 'admin' role
    op.bulk_insert(user_roles_table, [
        {'user_id': admin_user_id, 'role_id': admin_role_id},
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This downgrade will remove the admin user, the 'Administradores' group, and the 'admin' role.
    # Be cautious when running this in production.
    op.execute("DELETE FROM users WHERE email = 'admin@example.com'")
    op.execute("DELETE FROM groups WHERE name = 'Administradores'")
    op.execute("DELETE FROM roles WHERE name = 'admin'") # Assuming role name is 'admin'
    # ### end Alembic commands ###