"""add_dependency_and_technician_fields

Revision ID: 8ff34e617e47
Revises: 353cecd64b71
Create Date: 2026-01-28 10:33:29.674810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff34e617e47'
down_revision: Union[str, None] = '353cecd64b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_install_records', sa.Column('tecnico_instalacion', sa.String(length=255), nullable=True))
    op.add_column('asset_install_records', sa.Column('tecnico_carga', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('dependencia', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('codigo_dependencia', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'codigo_dependencia')
    op.drop_column('assets', 'dependencia')
    op.drop_column('asset_install_records', 'tecnico_carga')
    op.drop_column('asset_install_records', 'tecnico_instalacion')
    # ### end Alembic commands ###
