"""Add hidden_nav_items to Group model

Revision ID: a70cf7b2a000
Revises: 4511119088ae
Create Date: 2026-01-26 17:14:59.514400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a70cf7b2a000'
down_revision: Union[str, None] = '4511119088ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('hidden_nav_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE groups SET hidden_nav_items = '[]'::jsonb WHERE hidden_nav_items IS NULL")
    op.alter_column('groups', 'hidden_nav_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'hidden_nav_items')
    # ### end Alembic commands ###
