"""Add assigned_to_id to Alert

Revision ID: baaaadb54c91
Revises: f01810c0274a
Create Date: 2026-02-08 13:17:35.800682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baaaadb54c91'
down_revision: Union[str, None] = 'f01810c0274a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('assigned_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'assigned_to_id')
    # ### end Alembic commands ###
