"""link_ticket_to_asset

Revision ID: c2c47c740150
Revises: 02159e1c930c
Create Date: 2026-01-24 12:47:41.939126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c47c740150'
down_revision: Union[str, None] = '02159e1c930c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'asset_id')
    # ### end Alembic commands ###
