"""consolidate_manual_changes_and_wiki

Revision ID: c40000d870e6
Revises: c10dc1c2d32d
Create Date: 2026-02-16 23:48:57.836271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40000d870e6'
down_revision: Union[str, None] = 'c10dc1c2d32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'model')
    op.drop_column('assets', 'brand')
    op.drop_constraint('ticket_assets_asset_id_fkey', 'ticket_assets', type_='foreignkey')
    op.drop_constraint('ticket_assets_ticket_id_fkey', 'ticket_assets', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_assets', 'tickets', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'ticket_assets', 'assets', ['asset_id'], ['id'])
    op.drop_constraint('ticket_locations_ticket_id_fkey', 'ticket_locations', type_='foreignkey')
    op.drop_constraint('ticket_locations_location_id_fkey', 'ticket_locations', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_locations', 'location_nodes', ['location_id'], ['id'])
    op.create_foreign_key(None, 'ticket_locations', 'tickets', ['ticket_id'], ['id'])
    op.alter_column('wiki_pages', 'is_folder',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wiki_pages', 'is_folder',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'ticket_locations', type_='foreignkey')
    op.drop_constraint(None, 'ticket_locations', type_='foreignkey')
    op.create_foreign_key('ticket_locations_location_id_fkey', 'ticket_locations', 'location_nodes', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ticket_locations_ticket_id_fkey', 'ticket_locations', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'ticket_assets', type_='foreignkey')
    op.drop_constraint(None, 'ticket_assets', type_='foreignkey')
    op.create_foreign_key('ticket_assets_ticket_id_fkey', 'ticket_assets', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ticket_assets_asset_id_fkey', 'ticket_assets', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.add_column('assets', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
