"""add_enroll_2fa_mandatory

Revision ID: cb571bcf742d
Revises: a70cf7b2a000
Create Date: 2026-01-27 14:09:05.300320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb571bcf742d'
down_revision: Union[str, None] = 'a70cf7b2a000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enroll_2fa_mandatory', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET enroll_2fa_mandatory = False")
    op.alter_column('users', 'enroll_2fa_mandatory', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enroll_2fa_mandatory')
    # ### end Alembic commands ###
