"""v1_2_6_updates

Revision ID: d2e42badb9fc
Revises: 8ca16aa7894e
Create Date: 2026-01-23 21:45:48.416066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e42badb9fc'
down_revision: Union[str, None] = '8ca16aa7894e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status_key', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_initial', sa.Boolean(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_response_breached', sa.Boolean(), nullable=True),
    sa.Column('is_resolution_breached', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['sla_policies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sla_policies', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('sla_policies', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('sla_policies', sa.Column('ticket_type_id', sa.UUID(), nullable=True))
    op.add_column('sla_policies', sa.Column('business_hours', sa.JSON(), nullable=True))
    op.drop_constraint('sla_policies_priority_key', 'sla_policies', type_='unique')
    op.create_foreign_key(None, 'sla_policies', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'sla_policies', 'ticket_types', ['ticket_type_id'], ['id'])
    op.add_column('workflow_transitions', sa.Column('workflow_id', sa.UUID(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('from_state_id', sa.UUID(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('to_state_id', sa.UUID(), nullable=True))
    op.add_column('workflow_transitions', sa.Column('conditions', sa.JSON(), nullable=True))
    op.alter_column('workflow_transitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'workflow_transitions', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'workflow_transitions', 'workflow_states', ['from_state_id'], ['id'])
    op.create_foreign_key(None, 'workflow_transitions', 'workflow_states', ['to_state_id'], ['id'])
    op.drop_column('workflow_transitions', 'from_status')
    op.drop_column('workflow_transitions', 'to_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_transitions', sa.Column('to_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('workflow_transitions', sa.Column('from_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_transitions', type_='foreignkey')
    op.alter_column('workflow_transitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('workflow_transitions', 'conditions')
    op.drop_column('workflow_transitions', 'to_state_id')
    op.drop_column('workflow_transitions', 'from_state_id')
    op.drop_column('workflow_transitions', 'workflow_id')
    op.drop_constraint(None, 'sla_policies', type_='foreignkey')
    op.drop_constraint(None, 'sla_policies', type_='foreignkey')
    op.create_unique_constraint('sla_policies_priority_key', 'sla_policies', ['priority'])
    op.drop_column('sla_policies', 'business_hours')
    op.drop_column('sla_policies', 'ticket_type_id')
    op.drop_column('sla_policies', 'group_id')
    op.drop_column('sla_policies', 'description')
    op.drop_table('sla_metrics')
    op.drop_table('workflow_states')
    op.drop_table('workflows')
    # ### end Alembic commands ###
