"""Add resolution fields to Alert

Revision ID: f01810c0274a
Revises: 7ff5ae65813f
Create Date: 2026-02-08 13:10:26.328240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01810c0274a'
down_revision: Union[str, None] = '7ff5ae65813f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['resolved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'resolved_by_id')
    op.drop_column('alerts', 'resolved_at')
    # ### end Alembic commands ###
