"""Add AI analysis fields to alerts

Revision ID: f9b21018902c
Revises: fa31ffad8c0f
Create Date: 2026-02-04 23:41:07.557769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b21018902c'
down_revision: Union[str, None] = 'fa31ffad8c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('ai_remediation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'ai_remediation')
    op.drop_column('alerts', 'ai_summary')
    # ### end Alembic commands ###
